package myreika.weather.domain.enums.metrics;

public enum ApiCallType {

    DAILY_FORECAST,
    HOURLY_FORECAST,
    MINUTELY_FORECAST,
    WEATHER_ALERTS,
    CURRENT_WEATHER_BY_CITY,
    CURRENT_WEATHER_BY_ZIP_CODE,
    CURRENT_WEATHER_BY_CITY_ID,
    CURRENT_WEATHER_BY_COORDINATES
}
